import React from 'react';
import Card from '../components/Card';
import Button from '../components/Button';
import { Link } from 'react-router-dom';
import {
  ShieldAlert,
  AlertTriangle,
  FileCheck2,
  Stethoscope,
  HeartPulse,
  ArrowRight,
  Info,
} from 'lucide-react';

export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 space-y-8 animate-fadeIn">
      {/* Header */}
      <div className="text-center max-w-2xl mx-auto">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-50 border border-amber-200 text-xs font-semibold text-amber-800 mb-3">
          <ShieldAlert className="w-4 h-4 text-amber-600" />
          Regulatory & Clinical Notice
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
          Important Disclaimer
        </h1>
        <p className="text-slate-600 text-sm sm:text-base mt-2">
          Please read this clinical notice carefully before utilizing the CardioML prediction tool.
        </p>
      </div>

      {/* Primary Warning Banner Card */}
      <Card className="border-amber-200 bg-gradient-to-br from-amber-50/70 via-white to-amber-50/30 shadow-md">
        <div className="flex items-start gap-4">
          <div className="p-3 rounded-2xl bg-amber-100 text-amber-700 shrink-0">
            <AlertTriangle className="w-6 h-6" />
          </div>
          <div className="space-y-2">
            <h2 className="text-lg font-bold text-amber-950">
              Not a Medical Diagnosis Tool
            </h2>
            <p className="text-sm text-amber-900 leading-relaxed">
              This system is an <strong>educational machine learning project</strong> designed to demonstrate binary risk classification pipelines. The outputs generated by this application are mathematical approximations derived from historical epidemiological datasets and <strong>do not constitute medical diagnoses, clinical determinations, or personalized health recommendations</strong>.
            </p>
          </div>
        </div>
      </Card>

      {/* Detail Sections */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Card 1: Model Nature */}
        <Card className="border-slate-200 shadow-sm">
          <div className="flex items-center gap-2 mb-3">
            <HeartPulse className="w-5 h-5 text-blue-600" />
            <h3 className="text-base font-bold text-slate-900">
              Machine Learning Limitations
            </h3>
          </div>
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
            The predictions are generated by an existing trained ML model (Logistic Regression) with StandardScaler preprocessing. While trained on 70,000 anonymized clinical examination records, statistical models may not account for individual medical history, genetic predispositions, medications, or comorbid health conditions.
          </p>
        </Card>

        {/* Card 2: Clinical Consultation */}
        <Card className="border-slate-200 shadow-sm">
          <div className="flex items-center gap-2 mb-3">
            <Stethoscope className="w-5 h-5 text-blue-600" />
            <h3 className="text-base font-bold text-slate-900">
              Consult a Physician
            </h3>
          </div>
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
            Never disregard professional medical guidance, delay seeking medical attention, or alter prescribed cardiovascular medications based on outputs generated by this system. If you experience chest pain, shortness of breath, or dizziness, seek immediate emergency medical care.
          </p>
        </Card>
      </div>

      {/* Structured Guidelines */}
      <Card className="border-slate-200 shadow-sm">
        <h3 className="text-base font-bold text-slate-900 mb-4 flex items-center gap-2">
          <FileCheck2 className="w-5 h-5 text-blue-600" />
          Key Usage Guidelines
        </h3>
        <ul className="space-y-3 text-xs sm:text-sm text-slate-600">
          <li className="flex items-start gap-2.5">
            <span className="w-1.5 h-1.5 rounded-full bg-blue-600 mt-2 shrink-0" />
            <span>
              <strong>Research & Academic Intent:</strong> This application is intended for academic demonstrations, bioinformatics coursework, and technical evaluation of ML deployment architecture.
            </span>
          </li>
          <li className="flex items-start gap-2.5">
            <span className="w-1.5 h-1.5 rounded-full bg-blue-600 mt-2 shrink-0" />
            <span>
              <strong>No Patient Data Retention:</strong> Inputs submitted into the form are processed ephemerally in memory by the REST API and are not stored in any external database.
            </span>
          </li>
          <li className="flex items-start gap-2.5">
            <span className="w-1.5 h-1.5 rounded-full bg-blue-600 mt-2 shrink-0" />
            <span>
              <strong>Diagnostic Authority:</strong> Only qualified cardiologists, internists, and general practitioners possess the clinical tools, diagnostic tests (ECG, echocardiograms, blood chemistry panels), and legal mandate to diagnose cardiovascular pathology.
            </span>
          </li>
        </ul>
      </Card>

      {/* Back to Home / Assessment Button */}
      <div className="flex justify-center pt-4">
        <Link to="/assessment">
          <Button variant="orange" size="lg" icon={ArrowRight}>
            Proceed to Assessment
          </Button>
        </Link>
      </div>
    </div>
  );
}
