import React, { useState } from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import Card from '../components/Card';
import Button from '../components/Button';
import ProbabilityRing from '../components/ProbabilityRing';
import PatientSummary from '../components/PatientSummary';
import {
  CheckCircle2,
  AlertTriangle,
  ArrowLeft,
  RotateCcw,
  ShieldAlert,
  Sparkles,
  Info,
  Stethoscope,
  Printer,
  Copy,
  Check,
  HeartPulse,
  Scale,
  Gauge,
  Activity,
  Flame,
  FileText,
} from 'lucide-react';

export default function ResultPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const [copied, setCopied] = useState(false);

  const stateData = location.state;
  const result = stateData?.result;
  const patientData = stateData?.patientData;

  // Fallback if accessed directly without prediction
  if (!result) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-16 text-center">
        <Card className="border-slate-200">
          <div className="w-16 h-16 rounded-2xl bg-blue-50 text-blue-600 flex items-center justify-center mx-auto mb-4">
            <Stethoscope className="w-8 h-8" />
          </div>
          <h2 className="text-2xl font-bold text-slate-900">No Assessment Found</h2>
          <p className="text-slate-600 text-sm mt-2 mb-6 max-w-md mx-auto">
            Please complete the assessment form with patient health indicators to view real machine learning prediction results.
          </p>
          <Link to="/assessment">
            <Button variant="primary" icon={RotateCcw}>
              Go to Assessment
            </Button>
          </Link>
        </Card>
      </div>
    );
  }

  const isHigherRisk = result.prediction === 1;

  // Derived Clinical Metrics
  const heightM = patientData?.height ? parseFloat(patientData.height) / 100 : 0;
  const weightKg = patientData?.weight ? parseFloat(patientData.weight) : 0;
  const bmi = heightM > 0 ? (weightKg / (heightM * heightM)).toFixed(1) : null;

  let bmiCategory = 'Normal';
  let bmiColor = 'text-emerald-700 bg-emerald-50 border-emerald-200';
  if (bmi) {
    const bmiNum = parseFloat(bmi);
    if (bmiNum < 18.5) {
      bmiCategory = 'Underweight';
      bmiColor = 'text-amber-700 bg-amber-50 border-amber-200';
    } else if (bmiNum < 25) {
      bmiCategory = 'Normal Weight';
      bmiColor = 'text-emerald-700 bg-emerald-50 border-emerald-200';
    } else if (bmiNum < 30) {
      bmiCategory = 'Overweight';
      bmiColor = 'text-amber-700 bg-amber-50 border-amber-200';
    } else {
      bmiCategory = 'Obese';
      bmiColor = 'text-red-700 bg-red-50 border-red-200';
    }
  }

  // Blood Pressure Classification
  const systolic = patientData?.ap_hi ? parseFloat(patientData.ap_hi) : 0;
  const diastolic = patientData?.ap_lo ? parseFloat(patientData.ap_lo) : 0;
  let bpStage = 'Normal BP';
  let bpColor = 'text-emerald-700 bg-emerald-50 border-emerald-200';

  if (systolic >= 140 || diastolic >= 90) {
    bpStage = 'Stage 2 Hypertension';
    bpColor = 'text-red-700 bg-red-50 border-red-200';
  } else if ((systolic >= 130 && systolic <= 139) || (diastolic >= 80 && diastolic <= 89)) {
    bpStage = 'Stage 1 Hypertension';
    bpColor = 'text-orange-700 bg-orange-50 border-orange-200';
  } else if (systolic >= 120 && systolic <= 129 && diastolic < 80) {
    bpStage = 'Elevated BP';
    bpColor = 'text-amber-700 bg-amber-50 border-amber-200';
  }

  // Copy Summary Handler
  const handleCopySummary = () => {
    if (!patientData || !result) return;
    const text = `CardioML Risk Assessment Report
=================================
Classification: ${result.risk} (Cardio=${result.prediction})
Estimated Probability: ${result.probability ? (result.probability * 100).toFixed(1) + '%' : 'N/A'}
Patient Profile:
- Age: ${patientData.age} | Gender: ${patientData.gender}
- Height: ${patientData.height} cm | Weight: ${patientData.weight} kg (BMI: ${bmi || 'N/A'})
- Blood Pressure: ${patientData.ap_hi}/${patientData.ap_lo} mmHg (${bpStage})
- Cholesterol: ${patientData.cholesterol} | Glucose: ${patientData.gluc}
- Smoking: ${patientData.smoke} | Alcohol: ${patientData.alco} | Active: ${patientData.active}
Advisory: ${result.message}
Generated by CardioML Platform.`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 space-y-8 animate-fadeIn">
      {/* Top Action Bar (Print / Copy / Tag) */}
      <div className="flex flex-wrap items-center justify-between gap-4 no-print border-b border-slate-200/80 pb-4">
        <Link
          to="/assessment"
          className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-600 hover:text-blue-600 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Assessment Form
        </Link>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleCopySummary}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 bg-white text-xs font-medium text-slate-700 hover:bg-slate-50 shadow-sm transition-all"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-600" />
                <span className="text-emerald-600 font-semibold">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-slate-500" />
                <span>Copy Summary</span>
              </>
            )}
          </button>
          <button
            type="button"
            onClick={() => window.print()}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 bg-white text-xs font-medium text-slate-700 hover:bg-slate-50 shadow-sm transition-all"
          >
            <Printer className="w-3.5 h-3.5 text-slate-500" />
            <span>Print Report</span>
          </button>
        </div>
      </div>

      {/* Page Header */}
      <div className="text-center max-w-2xl mx-auto">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-slate-100 border border-slate-200 text-xs font-semibold text-slate-700 mb-3">
          <Sparkles className="w-3.5 h-3.5 text-blue-600" />
          Real-Time Machine Learning Output
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
          Cardiovascular Risk Report
        </h1>
        <p className="text-slate-600 text-sm sm:text-base mt-1">
          Evaluated via trained LogisticRegression model with verified clinical parameters
        </p>
      </div>

      {/* Primary Result Banner Card */}
      <Card
        className={`border-2 shadow-xl transition-card ${
          isHigherRisk
            ? 'border-red-200 bg-gradient-to-br from-red-50/70 via-white to-white'
            : 'border-emerald-200 bg-gradient-to-br from-emerald-50/70 via-white to-white'
        }`}
      >
        <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-center">
          {/* Left: Risk Indicator & Decision */}
          <div className="md:col-span-7 space-y-4">
            <div className="flex items-center gap-3">
              <div
                className={`w-14 h-14 rounded-2xl flex items-center justify-center shrink-0 shadow-sm ${
                  isHigherRisk
                    ? 'bg-red-100 text-red-600 ring-4 ring-red-50'
                    : 'bg-emerald-100 text-emerald-600 ring-4 ring-emerald-50'
                }`}
              >
                {isHigherRisk ? (
                  <AlertTriangle className="w-8 h-8" />
                ) : (
                  <CheckCircle2 className="w-8 h-8" />
                )}
              </div>
              <div>
                <span
                  className={`text-xs font-bold uppercase tracking-wider flex items-center gap-1.5 ${
                    isHigherRisk ? 'text-red-600' : 'text-emerald-700'
                  }`}
                >
                  <span
                    className={`w-2 h-2 rounded-full animate-pulse-subtle ${
                      isHigherRisk ? 'bg-red-600' : 'bg-emerald-600'
                    }`}
                  />
                  Clinical Outcome
                </span>
                <h2
                  className={`text-3xl sm:text-4xl font-extrabold tracking-tight ${
                    isHigherRisk ? 'text-red-700' : 'text-emerald-800'
                  }`}
                >
                  {isHigherRisk ? 'Higher Risk' : 'Lower Risk'}
                </h2>
              </div>
            </div>

            {/* Model Tag */}
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-100/90 border border-slate-200 text-xs font-mono font-medium text-slate-700">
              <span>Classifier Prediction:</span>
              <strong className={isHigherRisk ? 'text-red-600' : 'text-emerald-700'}>
                Cardio = {result.prediction}
              </strong>
            </div>

            {/* Advisory Message */}
            <p className="text-sm sm:text-base font-medium text-slate-700 leading-relaxed">
              {result.message}
            </p>

            {isHigherRisk ? (
              <div className="p-3.5 rounded-xl bg-red-100/70 border border-red-200 text-xs text-red-900 leading-relaxed flex items-start gap-2.5">
                <Info className="w-4 h-4 shrink-0 text-red-600 mt-0.5" />
                <span>
                  The model identified physiological indicators commonly associated with cardiovascular pathology. A formal clinical consultation with electrocardiogram (ECG) and lipid screening is advised.
                </span>
              </div>
            ) : (
              <div className="p-3.5 rounded-xl bg-emerald-100/60 border border-emerald-200 text-xs text-emerald-900 leading-relaxed flex items-start gap-2.5">
                <CheckCircle2 className="w-4 h-4 shrink-0 text-emerald-600 mt-0.5" />
                <span>
                  Patient parameters currently align with lower statistical risk in the trained dataset. Maintain routine health checks and a balanced cardiovascular lifestyle.
                </span>
              </div>
            )}
          </div>

          {/* Right: Probability Gauge Ring */}
          <div className="md:col-span-5 flex flex-col items-center justify-center border-t md:border-t-0 md:border-l border-slate-100 pt-6 md:pt-0 md:pl-8">
            <div className="text-center mb-2">
              <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">
                Model Probability Score
              </span>
            </div>
            <ProbabilityRing
              probability={result.probability}
              isHigherRisk={isHigherRisk}
              size={175}
              strokeWidth={14}
            />
            <p className="text-[11px] text-slate-500 mt-2 text-center">
              Evaluated with Scikit-Learn LogisticRegression <br />
              <code className="text-slate-400">model.predict_proba()</code>
            </p>
          </div>
        </div>
      </Card>

      {/* Clinical Diagnostic Indicators Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        {/* Blood Pressure Stage Card */}
        <div className="p-4 rounded-2xl bg-white border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between text-xs text-slate-500 mb-1.5">
            <span className="font-semibold flex items-center gap-1.5">
              <Gauge className="w-4 h-4 text-blue-600" />
              Blood Pressure
            </span>
            <span className={`px-2 py-0.5 rounded-full text-[11px] font-bold border ${bpColor}`}>
              {bpStage}
            </span>
          </div>
          <div className="text-xl font-extrabold text-slate-900">
            {patientData.ap_hi} / {patientData.ap_lo} <span className="text-xs font-normal text-slate-500">mmHg</span>
          </div>
          <p className="text-[11px] text-slate-500 mt-1">
            {systolic >= 140 ? 'Stage 2 requires medical oversight' : 'Within monitored baseline'}
          </p>
        </div>

        {/* BMI Card */}
        <div className="p-4 rounded-2xl bg-white border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between text-xs text-slate-500 mb-1.5">
            <span className="font-semibold flex items-center gap-1.5">
              <Scale className="w-4 h-4 text-indigo-600" />
              Body Mass Index
            </span>
            <span className={`px-2 py-0.5 rounded-full text-[11px] font-bold border ${bmiColor}`}>
              {bmiCategory}
            </span>
          </div>
          <div className="text-xl font-extrabold text-slate-900">
            {bmi || '--'} <span className="text-xs font-normal text-slate-500">kg/m²</span>
          </div>
          <p className="text-[11px] text-slate-500 mt-1">
            Calculated from {patientData.height} cm & {patientData.weight} kg
          </p>
        </div>

        {/* Lifestyle Profile Card */}
        <div className="p-4 rounded-2xl bg-white border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between text-xs text-slate-500 mb-1.5">
            <span className="font-semibold flex items-center gap-1.5">
              <Activity className="w-4 h-4 text-emerald-600" />
              Lifestyle & Habits
            </span>
            <span
              className={`px-2 py-0.5 rounded-full text-[11px] font-bold border ${
                patientData.smoke === 'Yes' || patientData.active === 'No'
                  ? 'text-amber-700 bg-amber-50 border-amber-200'
                  : 'text-emerald-700 bg-emerald-50 border-emerald-200'
              }`}
            >
              {patientData.smoke === 'Yes' || patientData.active === 'No' ? 'Risk Factors' : 'Optimal'}
            </span>
          </div>
          <div className="text-xs text-slate-700 space-y-0.5 mt-2">
            <div>Smoking: <strong className={patientData.smoke === 'Yes' ? 'text-red-600' : 'text-emerald-600'}>{patientData.smoke}</strong></div>
            <div>Physical Activity: <strong className={patientData.active === 'Yes' ? 'text-emerald-600' : 'text-red-600'}>{patientData.active}</strong></div>
          </div>
        </div>
      </div>

      {/* Patient Summary Card */}
      <PatientSummary data={patientData} />

      {/* Medical Disclaimer Banner */}
      <div className="p-4 rounded-2xl bg-amber-50/80 border border-amber-200 flex items-start gap-3 text-xs text-amber-900 leading-relaxed shadow-sm">
        <ShieldAlert className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
        <div>
          <strong className="font-semibold block mb-0.5">Clinical Disclaimer:</strong>
          This platform utilizes machine learning for risk prediction and educational analysis. It is not an automated medical diagnostic tool. All clinical decisions must be supervised by certified medical professionals.
        </div>
      </div>

      {/* Navigation Buttons */}
      <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4 no-print">
        <Link to="/assessment" className="w-full sm:w-auto">
          <Button variant="orange" size="lg" icon={RotateCcw} className="w-full sm:w-auto">
            New Assessment
          </Button>
        </Link>
        <Link to="/" className="w-full sm:w-auto">
          <Button variant="outline" size="lg" icon={ArrowLeft} className="w-full sm:w-auto">
            Back to Home
          </Button>
        </Link>
      </div>
    </div>
  );
}
